### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by HANDZCZ** [HANDZCZ/genshin-stats#3]
Shows ``5 x ``, instead of correct artifacts (``2 x Pale Flame<br>2 x Bloodstained Chivalry<br>1 x Tenacity of the Millelith``).

EDIT: first the artifact replacing failed

**Comment by HANDZCZ** [comment]
Run after:

```
Traceback (most recent call last):
  File "./main.py", line 25, in <module>
    characters = gs.get_characters(GAME_UID)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/genshinstats.py", line 197, in get_characters
    return prettify_characters(data)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/pretty.py", line 128, in prettify_characters
    } for i in data]
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/pretty.py", line 128, in <listcomp>
    } for i in data]
KeyError: 101
```

**Comment by HANDZCZ** [comment]
Scheduled run next day:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bbs-api-os.hoyolab.com', port=443): Max retries exceeded with url: /community/apihub/api/signIn (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    gs.hoyolab_check_in()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/hoyolab.py", line 58, in hoyolab_check_in
    json=dict(gids=2)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/genshinstats.py", line 155, in fetch_endpoint
    return _request(method, url, cookies=cookie, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/genshinstats.py", line 121, in _request
    r = session.request(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bbs-api-os.hoyolab.com', port=443): Max retries exceeded with url: /community/apihub/api/signIn (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')))
```

**Comment by HANDZCZ** [comment]
Run after:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 27, in <module>
    (daily_reward_info_is_sign, daily_reward_info_total_sign_day) = gs.get_daily_reward_info()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/daily.py", line 36, in get_daily_reward_info
    data = fetch_daily_endpoint("info", chinese, cookie=cookie)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/daily.py", line 28, in fetch_daily_endpoint
    return fetch_endpoint(url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/genshinstats.py", line 155, in fetch_endpoint
    return _request(method, url, cookies=cookie, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/genshinstats/genshinstats.py", line 121, in _request
    r = session.request(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by HANDZCZ** [comment]
Tested the same code locally and it works perfectly ¯\_(ツ)_/¯
So the issue is somewhere in Github actions.

**Comment by HANDZCZ** [comment]
Disabled and enabled the workflow. Now it works again.
